### PR TITLE
blocked pandas useragent by the worldometers.info

### PR DESCRIPTION
**Pull request by blka**
change to requests with fake user-agent

### CODE REVIEW

**Comment by mrbitsdcf** [comment]
Hello. Thanks a lot for your contribution. 

Could you please explain why in PR #2 you removed line df = pd.read_html(url, index_col=0)[0] and in PR #3 you put it back?

Many thanks.

**Comment by blka** [comment]
seems like cannot into github... :/

**Comment by blka** [comment]
looks better now, pls check

**Comment by rickkbarbosa** [comment]
Hello,


Fixed it :)

Other guy (@everaldoscabral ) submitted a solution using requests, that solves 403 issues too. 
I've merged in the changes and it's available to pull.

**Pull request closed without merging**
